### ISSUE TITLE
Installer Fails, Please run first boot installer on TMUX

### ISSUE THREAD

**Issue by skye-vapro** [home-assistant/hassbian-scripts#29]
This will allow the end user to hop on SSH and open the TMUX window. Even better, have it setup as a pi login script to open the tmux window if this is the first boot.

**Comment by Landrash** [comment]
Since the first run installer is run as a service that won't be possible and not something I will do.
If you got good way of doing this that won't break any of the existing functionality please submit a pull request.
Ensure that your Pi has a wired functioning internet connection and it should work. I've so far not been able to make it fail once and the situations I've helped diagnose has been problems with end-users routers, dns not resolving and so on.
