### ISSUE TITLE
Webterminal Hassbian Script Over HTTPS 

### ISSUE THREAD

**Issue by carlostico** [home-assistant/hassbian-scripts#74]
Webterminal Script for Hassbian is great but it does not work over HTTPS 
The script uses shellinabox and that has support for ssl  ... anyone ??

**Comment by ludeeus** [comment]
I now have it working in Firefox, but had to add an exeption due to missing cert.
![bilde](https://user-images.githubusercontent.com/15093472/33313068-fc66a0d8-d429-11e7-8777-0d57e18af1b7.png)

In chrome I get this:
![bilde](https://user-images.githubusercontent.com/15093472/33313174-38f583d4-d42a-11e7-96ac-8daa92f0ac63.png)

If I expose the port I could probably use my LetsEncrypt Cert, but I do not want ssh to be open from outside my network.

There is an option for self-signed cert, but Chrome don't like those..

@Landrash, do you have some idea on how to takle this?

**Comment by Landrash** [comment]
@ludeeus You need to add that exception since it from "another domain" in chrome.

You could use the same Cert on both of them.

[This](https://github.com/shellinabox/shellinabox/pull/411/files) could be of some help to add the Let's Encrypt cert.

**Comment by Landrash** [comment]
Closing since this is an enchantment that needs to be included upstream.  https://github.com/shellinabox/shellinabox/pull/411 is suggested as a fix but has yet to be merged.

**Comment by juan11perez** [comment]
@ludeeus 
After days of trial and error I found a way to get Shellinabox on https using the letsencrypt certificate:
Enabled ssl by confirming sudo nano /etc/default/shellinabox with:
SHELLINABOX_ARGS="--no-beep" 
I then made a copy of my fullchain.pem in /etc/letsencrypt/live/mydomain.duckdns.org. 
to that copy which I named certificate-mydomain.duckdns.org.pem I added at the top the content of my privkey.pem.
I then created a symlink as such:
sudo ln -sf /etc/letsencrypt/live/mydomain.duckdns.org/certificate-juan11perez.duckdns.org.
pem /var/lib/shellinabox/certificate-mydomain.duckdns.org.pem
restarted shellinabox - sudo invoke-rc.d shellinabox restart
and opened in chrome. no errors or warnings. see below

![shellinabox](https://user-images.githubusercontent.com/30061229/36399154-09839478-15e4-11e8-94dc-2b11ff33dff9.jpg)

is there a way to create a symlink of both certificates/file fullchain.pem and privkey.pem to /var/lib/shellinabox/certificate-mydomain.duckdns.org.pem to avoid making a copy and also keeping valid as letsencrypt renews?
