### ISSUE TITLE
Incorrect upgrade instructions for 0.7.0 - Need to specify 'hassbian-script-dev'

### ISSUE THREAD

**Issue by brianjking** [home-assistant/hassbian-scripts#95]
The upgrade instructions are incorrect for upgrading to `hassbian-script` version `0.7.0`. The instructions seen [here](https://github.com/home-assistant/hassbian-scripts/releases/tag/v0.7.0) indicate to run the following command:

`sudo hassbian-config upgrade hassbian-script`

However, since this release is tagged as pre-release you'd need to execute 

`sudo hassbian-config upgrade hassbian-script-dev`

Thanks!

**Comment by ludeeus** [comment]
@brianjking The instructions are intended for use when the release is published (not pre-release).
`sudo hassbian-config upgrade hassbian-script-dev` will not give you 0.7.0, but most of it.

It is best to wait for release to be done, since we are still testing, bu if you want to get the package now you can run this to install the pre-release:
```
$ wget https://github.com/home-assistant/hassbian-scripts/releases/download/v0.7.0/hassbian-scripts_0.7.0.deb
$ sudo apt install ./hassbian-scripts_0.7.0.deb
```
But I encourage you to wait for release.
